export const USER_POST_REQUEST = "USER_POST_REQUEST";
export const USER_POST_SUCCESS = "USER_POST_SUCCESS";
export const USER_POST_FAIL = "USER_POST_FAIL";

export const USER_GET_POST_REQUEST = "USER_GET_POST_REQUEST";
export const USER_GET_POST_SUCCESS = "USER_GET_POST_SUCCESS";
export const USER_GET_POST_FAIL = "USER_GET_POST_FAIL";
